# -*- coding: utf-8 -*-
"""SentimentAnalysisDash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1YQsAZi7ju4ig3M3W4rF3iIpJcpyy59
"""

#pip install dash
import base64
import io
import dash
from dash import dcc, html, Input, Output, State
import pandas as pd
import plotly.express as px
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Initialize NLTK components (download if not already present)
import nltk
# Only download if not already downloaded to avoid unnecessary downloads
#nltk.download('all')
#try:
nltk.data.find('sentiment/vader_lexicon.zip')
#except LookupError:
#    nltk.download('vader_lexicon')
#try:
nltk.data.find('tokenizers/punkt')
#except LookupError:
#    nltk.download('punkt')
#try:
nltk.data.find('corpora/stopwords')
#except LookupError:
 #   nltk.download('stopwords')
try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')

# ===============================
# ===== DASH APP SETUP ==========
# ===============================

#app = dash.Dash(__name__, external_stylesheets=[dbc.themes.FLATLY])
app = dash.Dash(__name__)

app.title = "Sentiment Analysis Dash App"

server = app.server

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Online Retail Customer Feedback Sentiment Analysis"),
    dcc.Upload(
        id='upload-data',
        children=html.Div([
            'Drag and Drop or ',
            html.A('Select Files')
        ]),
        style={
            'width': '100%',
            'height': '60px',
            'lineHeight': '60px',
            'borderWidth': '1px',
            'borderStyle': 'dashed',
            'borderRadius': '5px',
            'textAlign': 'center',
            'margin': '10px'
        },
        multiple=False
    ),
    html.Div(id='output-data-upload'),
    html.Div(id='sentiment-graph-output'),
    html.Div(id='satisfaction-rate-output'),
    html.H2("Positive Review Word Cloud"),
    html.Div(id='positive-wordcloud-output'),
    html.H2("Negative Review Word Cloud"),
    html.Div(id='negative-wordcloud-output')
])


# Define preprocessing functions (reusing the ones from your notebook)
lemmatizer = WordNetLemmatizer()
sid = SentimentIntensityAnalyzer()

def preprocess_text_vader(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s!?]', '', text)
    custom_stop_words = {"drink","drinks","starbucks","coffee","store"}
    tokens = text.split()
    tokens = [word for word in tokens if word not in custom_stop_words]
    cleaned_text = ' '.join(tokens)
    return cleaned_text

def create_wordcloud_image(text):
    if not text.strip(): # Handle empty text to avoid errors
        return ''
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
    img = io.BytesIO()
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.savefig(img, format='png', bbox_inches='tight')
    plt.close() # Close the plot to free up memory
    img.seek(0)
    return 'data:image/png;base64,' + base64.b64encode(img.getvalue()).decode()


@app.callback(Output('output-data-upload', 'children'),
              Output('sentiment-graph-output', 'children'),
              Output('satisfaction-rate-output', 'children'),
              Output('positive-wordcloud-output', 'children'),
              Output('negative-wordcloud-output', 'children'),
              Input('upload-data', 'contents'),
              State('upload-data', 'filename'),
              State('upload-data', 'last_modified'))
def update_output(contents, filename, last_modified):
    if contents is not None:
        content_type, content_string = contents.split(',')

        decoded = base64.b64decode(content_string)
        try:
            if 'csv' in filename:
                # Assume that the user uploads a CSV file
                df_uploaded = pd.read_csv(io.StringIO(decoded.decode('utf-8')))
            else:
                return html.Div('Please upload a CSV file.', style={'color': 'red'}), None, None, None, None
        except Exception as e:
            print(e)
            return html.Div('There was an error processing this file.', style={'color': 'red'}), None, None, None, None

        # Assuming the feedback column is the first one or named 'col_1'
        # We need to handle cases where the CSV might not have a header or a specific column name
        if df_uploaded.shape[1] == 1: # If only one column is detected, assume it's the feedback
            feedback_column = df_uploaded.iloc[:, 0].name if df_uploaded.columns.tolist() else 0 # Get column name or index 0
        elif 'col_1' in df_uploaded.columns:
            feedback_column = 'col_1'
        elif df_uploaded.columns[0] == df_uploaded.iloc[0,0]: # Check if the first cell is also the header
            # This implies the first row might be data, not header
            df_uploaded.columns = [f'col_{i}' for i in range(df_uploaded.shape[1])]
            feedback_column = 'col_0' # Assuming feedback is in the first column
        else:
            feedback_column = df_uploaded.columns[0]

        df_uploaded['Cleaned_Review'] = df_uploaded[feedback_column].apply(preprocess_text_vader)
        df_uploaded['Compound_Score'] = df_uploaded['Cleaned_Review'].apply(lambda x: sid.polarity_scores(x)['compound'])
        df_uploaded['Sentiment'] = df_uploaded['Compound_Score'].apply(lambda c: 'Positive' if c > 0.05 else ('Negative' if c < -0.05 else 'Neutral'))

        sentiment_counts = df_uploaded['Sentiment'].value_counts().reset_index()
        sentiment_counts.columns = ['Sentiment', 'Count']

        fig = px.bar(sentiment_counts, x='Sentiment', y='Count',
                     color='Sentiment', title='Sentiment Distribution',
                     color_discrete_map={'Positive':'green', 'Neutral':'orange', 'Negative':'red'})

        positive_count = sentiment_counts[sentiment_counts['Sentiment'] == 'Positive']['Count'].sum()
        total_reviews = sentiment_counts['Count'].sum()
        satisfaction_rate = (positive_count / total_reviews * 100) if total_reviews > 0 else 0

        # Generate Word Clouds
        positive_reviews_text = ' '.join(df_uploaded[df_uploaded['Sentiment'] == 'Positive']['Cleaned_Review'].dropna().tolist())
        negative_reviews_text = ' '.join(df_uploaded[df_uploaded['Sentiment'] == 'Negative']['Cleaned_Review'].dropna().tolist())

        positive_wordcloud_src = create_wordcloud_image(positive_reviews_text)
        negative_wordcloud_src = create_wordcloud_image(negative_reviews_text)

        return (
            html.Div(f'File: {filename} processed successfully. Displaying results...'),
            dcc.Graph(figure=fig),
            html.Div(f'Satisfaction Rate: {satisfaction_rate:.2f}%', style={'fontSize': 20, 'textAlign': 'center', 'marginTop': '20px'}),
            html.Img(src=positive_wordcloud_src) if positive_wordcloud_src else html.Div('No positive reviews to display word cloud.'),
            html.Img(src=negative_wordcloud_src) if negative_wordcloud_src else html.Div('No negative reviews to display word cloud.')
        )
    return html.Div('Upload a CSV file to see the sentiment analysis.'), None, None, None, None

# ===============================
# ========= RUN APP =============
# ===============================

if __name__ == '__main__':
    #app.run_server(debug=True)
    import webbrowser
    from threading import Timer

    url = "http://0.0.0.0"
    Timer(1, lambda: webbrowser.open(url)).start()

    #app.run_server(debug=True)
    app.run(debug=True)